[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "public, max-age=300, stale-while-revalidate=3600"

[[headers]]
for = "/*/index.html"
[headers.values]
Cache-Control = "public, max-age=300, stale-while-revalidate=3600"

[[headers]]
for = "/*/*/index.html"
[headers.values]
Cache-Control = "public, max-age=300, stale-while-revalidate=3600"

[[headers]]
for = "/media/projects/*.mp4"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/media/projects/*.webm"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

# Redirects for legacy portfolio routes to support old links
[[redirects]]
from = "/portfolio"
to = "/projects"
status = 301
force = true

[[redirects]]
from = "/portfolio/*"
to = "/projects/:splat"
status = 301
force = true

# Contact routes
[[redirects]]
from = "/linkedin"
to = "https://www.linkedin.com/in/ppiech/"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/Tenemo"
status = 301

[[redirects]]
from = "/telegram"
to = "https://t.me/tenemo"
status = 301

[[redirects]]
from = "/discord"
to = "https://discord.com/users/297930621760831488"
status = 301
