[[headers]]
for = "/index.html"
[headers.values]
cache-control = "public, max-age=300, stale-while-revalidate=3600"

[[headers]]
for = "/*/index.html"
[headers.values]
cache-control = "public, max-age=300, stale-while-revalidate=3600"

[[headers]]
for = "/*/*/index.html"
[headers.values]
cache-control = "public, max-age=300, stale-while-revalidate=3600"


[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

[[redirects]]
from = "/media/logos/:file"
to = "/.netlify/images?url=/media/logos/:file&w=128"
status = 200
force = true

[[redirects]]
from = "/linkedin"
to = "https://www.linkedin.com/in/ppiech/"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/Tenemo"
status = 301

[[redirects]]
from = "/telegram"
to = "https://t.me/tenemo"
status = 301

[[redirects]]
from = "/discord"
to = "https://discord.com/users/297930621760831488"
status = 301

[[redirects]]
from = "/*"
to = "/"
status = 301
force = true
