# Netlify configuration
# Default build command uses the package.json script.
# We intentionally do NOT set a default publish dir here so production stays
# controlled by the Netlify UI setting (keeps live prod unchanged).
[build]
command = "npm run build"

# Branch-specific override: for the `ssg` branch, publish from dist/client
# (React Router build outputs static assets there for this branch).
[context."ssg"]
publish = "dist/client"

# SPA routing is handled via public/_redirects, which is included in the build output.
# Example there: `/*  /__spa-fallback.html  200`
