/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const card: string;
declare const description: string;
declare const dateBadge: string;
declare const previewContainer: string;
declare const image: string;
declare const content: string;
declare const projectTitle: string;
declare const imageRight: string;
declare const imageLeft: string;

export {
	card,
	description,
	dateBadge,
	previewContainer,
	image,
	content,
	projectTitle,
	imageRight,
	imageLeft
};

declare const __default_export__: {
	card: typeof card;
	description: typeof description;
	dateBadge: typeof dateBadge;
	previewContainer: typeof previewContainer;
	image: typeof image;
	content: typeof content;
	projectTitle: typeof projectTitle;
	imageRight: typeof imageRight;
	imageLeft: typeof imageLeft;
};
export default __default_export__;
