/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const contactInfoContainer: string;
const main: string;
const contactItemsContainer: string;
const contactItem: string;

export {
	contactInfoContainer,
	main,
	contactItemsContainer,
	contactItem
};

export default {
	contactInfoContainer,
	main,
	contactItemsContainer,
	contactItem
};
