/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const contactInfoContainer: string;
const contactItem: string;
const main: string;

export {
	contactInfoContainer,
	contactItem,
	main
};

export default {
	contactInfoContainer,
	contactItem,
	main
};
