/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const portfolio: string;
const portfolioItemsContainer: string;

export {
	portfolio,
	portfolioItemsContainer
};

export default {
	portfolio,
	portfolioItemsContainer
};
