/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const portfolio: string;
declare const portfolioItemsContainer: string;

export {
	portfolio,
	portfolioItemsContainer
};

declare const __default_export__: {
	portfolio: typeof portfolio;
	portfolioItemsContainer: typeof portfolioItemsContainer;
};
export default __default_export__;
