/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const projects: string;
declare const projectsItemsContainer: string;

export {
	projects,
	projectsItemsContainer
};

declare const __default_export__: {
	projects: typeof projects;
	projectsItemsContainer: typeof projectsItemsContainer;
};
export default __default_export__;
