/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const markdownContainer: string;
declare const dateBadge: string;
declare const videoPlayer: string;
declare const markdownImage: string;
declare const codeBlock: string;
declare const inlineCode: string;

export {
	markdownContainer,
	dateBadge,
	videoPlayer,
	markdownImage,
	codeBlock,
	inlineCode
};

declare const __default_export__: {
	markdownContainer: typeof markdownContainer;
	dateBadge: typeof dateBadge;
	videoPlayer: typeof videoPlayer;
	markdownImage: typeof markdownImage;
	codeBlock: typeof codeBlock;
	inlineCode: typeof inlineCode;
};
export default __default_export__;
