/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const card: string;
const previewContainer: string;
const image: string;
const content: string;
const description: string;
const projectTitle: string;
const imageRight: string;
const imageLeft: string;
const loadingContainer: string;
const errorContainer: string;
const errorMessage: string;

export {
	card,
	previewContainer,
	image,
	content,
	description,
	projectTitle,
	imageRight,
	imageLeft,
	loadingContainer,
	errorContainer,
	errorMessage
};

export default {
	card,
	previewContainer,
	image,
	content,
	description,
	projectTitle,
	imageRight,
	imageLeft,
	loadingContainer,
	errorContainer,
	errorMessage
};
