/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const card: string;
const image: string;
const imageContainer: string;
const imageRight: string;
const imageLeft: string;
const content: string;

export {
	card,
	image,
	imageContainer,
	imageRight,
	imageLeft,
	content
};

export default {
	card,
	image,
	imageContainer,
	imageRight,
	imageLeft,
	content
};
