/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const card: string;
const imageContainer: string;
const image: string;
const content: string;
const description: string;
const imageRight: string;
const imageLeft: string;
const technologiesContainer: string;
const logo: string;
const wideLogo: string;
const loadingContainer: string;
const errorContainer: string;
const errorMessage: string;

export {
	card,
	imageContainer,
	image,
	content,
	description,
	imageRight,
	imageLeft,
	technologiesContainer,
	logo,
	wideLogo,
	loadingContainer,
	errorContainer,
	errorMessage
};

export default {
	card,
	imageContainer,
	image,
	content,
	description,
	imageRight,
	imageLeft,
	technologiesContainer,
	logo,
	wideLogo,
	loadingContainer,
	errorContainer,
	errorMessage
};
