/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const main: string;
const aboutMeDescription: string;
const buttonsContainer: string;
const dividerText: string;
const mainButton: string;
const contactButton: string;

export {
	main,
	aboutMeDescription,
	buttonsContainer,
	dividerText,
	mainButton,
	contactButton
};

export default {
	main,
	aboutMeDescription,
	buttonsContainer,
	dividerText,
	mainButton,
	contactButton
};
