/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const about: string;
const buttonsContainer: string;
const divider: string;
const dividerText: string;
const mainButton: string;
const contactButton: string;

export {
	about,
	buttonsContainer,
	divider,
	dividerText,
	mainButton,
	contactButton
};

export default {
	about,
	buttonsContainer,
	divider,
	dividerText,
	mainButton,
	contactButton
};
