/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const main: string;
declare const aboutMeDescription: string;
declare const buttonsContainer: string;
declare const dividerText: string;
declare const mainButton: string;
declare const contactButton: string;

export {
	main,
	aboutMeDescription,
	buttonsContainer,
	dividerText,
	mainButton,
	contactButton
};

declare const __default_export__: {
	main: typeof main;
	aboutMeDescription: typeof aboutMeDescription;
	buttonsContainer: typeof buttonsContainer;
	dividerText: typeof dividerText;
	mainButton: typeof mainButton;
	contactButton: typeof contactButton;
};
export default __default_export__;
