/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const app: string;
const error: string;
const errorInfo: string;

export {
	app,
	error,
	errorInfo
};

export default {
	app,
	error,
	errorInfo
};
