/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const logo: string;
declare const navigation: string;
declare const navLink: string;
declare const activeLink: string;

export {
	header,
	logo,
	navigation,
	navLink,
	activeLink
};

declare const __default_export__: {
	header: typeof header;
	logo: typeof logo;
	navigation: typeof navigation;
	navLink: typeof navLink;
	activeLink: typeof activeLink;
};
export default __default_export__;
