/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const header: string;
const logo: string;
const navigation: string;
const navLink: string;
const activeLink: string;

export {
	header,
	logo,
	navigation,
	navLink,
	activeLink
};

export default {
	header,
	logo,
	navigation,
	navLink,
	activeLink
};
