/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const githubLink: string;
const topBar: string;
const markdownContainer: string;
const videoContainer: string;
const videoPlayer: string;
const codeBlock: string;
const inlineCode: string;
const loading: string;
const error: string;

export {
	container,
	githubLink,
	topBar,
	markdownContainer,
	videoContainer,
	videoPlayer,
	codeBlock,
	inlineCode,
	loading,
	error
};

export default {
	container,
	githubLink,
	topBar,
	markdownContainer,
	videoContainer,
	videoPlayer,
	codeBlock,
	inlineCode,
	loading,
	error
};
