/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const footer: string;
declare const gitHubLink: string;

export {
	footer,
	gitHubLink
};

declare const __default_export__: {
	footer: typeof footer;
	gitHubLink: typeof gitHubLink;
};
export default __default_export__;
