/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const footer: string;
declare const githubLink: string;

export {
	footer,
	githubLink
};

declare const __default_export__: {
	footer: typeof footer;
	githubLink: typeof githubLink;
};
export default __default_export__;
