/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const footer: string;
const gitHubLink: string;

export {
	footer,
	gitHubLink
};

export default {
	footer,
	gitHubLink
};
