/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const backLink: string;
const markdownContainer: string;
const codeBlock: string;
const inlineCode: string;
const loading: string;
const error: string;

export {
	container,
	backLink,
	markdownContainer,
	codeBlock,
	inlineCode,
	loading,
	error
};

export default {
	container,
	backLink,
	markdownContainer,
	codeBlock,
	inlineCode,
	loading,
	error
};
