/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const markdownContainer: string;
const videoContainer: string;
const videoPlayer: string;
const codeBlock: string;
const inlineCode: string;

export {
	markdownContainer,
	videoContainer,
	videoPlayer,
	codeBlock,
	inlineCode
};

export default {
	markdownContainer,
	videoContainer,
	videoPlayer,
	codeBlock,
	inlineCode
};
