/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const githubLink: string;
declare const topBar: string;
declare const error: string;

export {
	container,
	githubLink,
	topBar,
	error
};

declare const __default_export__: {
	container: typeof container;
	githubLink: typeof githubLink;
	topBar: typeof topBar;
	error: typeof error;
};
export default __default_export__;
