/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const technologiesContainer: string;
declare const logo: string;
declare const wideLogo: string;

export {
	technologiesContainer,
	logo,
	wideLogo
};

declare const __default_export__: {
	technologiesContainer: typeof technologiesContainer;
	logo: typeof logo;
	wideLogo: typeof wideLogo;
};
export default __default_export__;
