/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const technologiesContainer: string;
const logo: string;
const wideLogo: string;

export {
	technologiesContainer,
	logo,
	wideLogo
};

export default {
	technologiesContainer,
	logo,
	wideLogo
};
